import { REPORT_KEY, REPORT_NAME } from "@models/const/reports.const";

export const REPORT_CONFIG = [
  {
    report: REPORT_KEY.REPSYNC_ERRORS,
    name: REPORT_NAME.REPSYNC_ERRORS,
    date: false,
    dateRange: false,
    subsidiary: false,
    zone: false,
    cdc: false,
    multicdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPDES_01,
    name: REPORT_NAME.REPDES_01,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    multicdc: true,
    cdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPMIX_01,
    name: `${REPORT_NAME.REPMIX_00}: ${REPORT_NAME.REPMIX_01}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    multicdc: true,
    cdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPMIX_02,
    name: `${REPORT_NAME.REPMIX_00}: ${REPORT_NAME.REPMIX_02}`,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    zone: true,
    cdc: true,
    customer: false,
  },
  {
    report: REPORT_KEY.REPVEN_01,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_01}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    multicdc: true,
    cdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPVEN_02,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_02}`,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    zone: true,
    cdc: true,
    customer: false,
  },
  {
    report: REPORT_KEY.REPVEN_03,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_03}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    multicdc: true,
    cdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPVEN_04,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_04}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    multicdc: true,
    cdc: false,
    customer: false,
  },
  {
    report: REPORT_KEY.REPVOI_01,
    name: REPORT_NAME.REPVOI_01,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    zone: true,
    cdc: true,
    customer: false,
  },
  {
    report: REPORT_KEY.REPCUP_01,
    name: REPORT_NAME.REPCUP_01,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    cdc: false,
    multicdc: true,
    customer: true,
  },
  {
    report: REPORT_KEY.REPBAN_01,
    name: REPORT_NAME.REPBAN_01,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    cdc: false,
    multicdc: true,
    customer: false,
  },
  {
    report: REPORT_KEY.REPBAN_02,
    name: REPORT_NAME.REPBAN_02,
    date: false,
    dateRange: true,
    subsidiary: true,
    zone: true,
    cdc: false,
    multicdc: true,
    customer: false,
  },
];

export const FILTER_LABELS = {
  date: 'Fecha',
  dateRange: 'Rango de fechas',
  subsidiary: 'Subsidiaria',
  zone: 'Zona',
  cdc: 'Centro de consumo',
  multicdc: 'Centros de consumo',
  customer: 'Ciente',
  employees: 'Empleados',
  approver: 'Aprobador',
  categories: 'Categorías',
  subcategories: 'Subcategorías',
  family: 'Familia',
  items: 'Artículos',
  paymentMethod: 'Método de pago',
  currency: 'Moneda',
  exchangeRate: 'Tipo de cambio'
};

export type FilterKey = keyof Omit<typeof REPORT_CONFIG[0], 'report' | 'name'>;