import { REPORT_KEY } from "@models/const/reports.const";

export const NUMBERTYPE_EXECPTION = ['quantity', 'id', 'cdcid', 'transactionid', 'attempts', 'key']

export const TABLE_CONFIG = [
  {
    report: REPORT_KEY.REPSYNC_ERRORS,
    headers: [
      { label: "ID", key: "id" },
      { label: "ID Transacción", key: "transactionID" },
      { label: "Estado", key: "especialStatus" },
      { label: "Intentos", key: "attempts" },
      { label: "Tipo", key: "type" },
      { label: "Mensaje de error", key: "errorMsg" },
      { label: "Centro de Consumo", key: "onCDC" },
      { label: "Proceso de Error", key: "processOfError" },
      { label: "Atendido", key: "attended" },
      { label: "Fecha/Hora Transacción", key: "creationDate" },
      { label: "Fecha/Hora de ultimo intento", key: "lastAttemptDate" },
    ],
  },
  {
    report: REPORT_KEY.REPDES_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Venta Ticket", key: "discountType" },
      { label: "Importe Descuentos", key: "discountAmount" },
      { label: "Venta Total", key: "totalSale" },
      { label: "% Descuentos / Venta Ticket", key: "discountPercentage" },
      { label: "Empleado", key: "employee" },
      { label: "Aprobador", key: "approver" },
    ],
  },
  {
    report: REPORT_KEY.REPMIX_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "subsidiary" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoria", key: "category" },
      { label: "Familia", key: "family" },
      { label: "Clave", key: "key" },
      { label: "Producto", key: "item" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "# items", key: "quantity" },
      { label: "% Ventas / Categoría", key: "categoryPercentage" },
      { label: "% Ventas / Familia", key: "familyPercentage" },
      { label: "Costo", key: "cost" },
      { label: "%Costo / Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPMIX_02,
    headers: [
      { label: "Fecha Ventas", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Empleado", key: "employee" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoría", key: "category" },
      { label: "Subcategoría", key: "subcategory" },
      { label: "Familia", key: "family" },
      { label: "Clave", key: "key" },
      { label: "Producto", key: "product" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "# items", key: "quantity" },
      { label: "Costo", key: "cost" },
      { label: "% Costo / Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Empleado", key: "employee" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Pax", key: "pax" },
      { label: "Venta/", key: "salePer" },
      { label: "# Cheques", key: "checksCount" },
      { label: "Cheque Promedio", key: "averageCheck" },
      { label: "Alimentos", key: "food" },
      { label: "Bebidas", key: "drinks" },
      { label: "Boutique", key: "boutique" },
      { label: "Fotos", key: "photos" },
      { label: "No clasificada", key: "unclassified" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_02,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoría", key: "category" },
      { label: "Subcategoría", key: "subcategory" },
      { label: "Familia", key: "family" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "% Venta Neta / Categoría", key: "netSalesCategoryPercentage" },
      { label: "% Venta / Total", key: "totalPercentage" },
      { label: "# items", key: "quantity" },
      { label: "Costo", key: "cost" },
      { label: "% Costo Vs Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_03,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Forma de Pago", key: "paymentMethod" },
      { label: "Moneda", key: "currency" },
      { label: "Tipo de cambio", key: "exchangeRate" },
      { label: "# Ticket", key: "ticketNumber" },
      { label: "Importe ($)", key: "amount" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Ventas Netas + IVA", key: "netSalesWithVAT" },
      { label: "Comentarios", key: "comments" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_04,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Presupuesto", key: "budget" },
      {
        label: "% Diferencia Vs Presupuesto",
        key: "budgetDifferencePercentage",
      },
      { label: "$ Diferencia Vs Presupuesto", key: "budgetDifferenceAmount" },
      { label: "Venta Año Anterior", key: "lastYearSale" },
      {
        label: "% Diferencia Vs Año Anterior",
        key: "lastYearDifferencePercentage",
      },
      { label: "Pax", key: "pax" },
      { label: "Venta / Paxs", key: "salePerPax" },
      { label: "Paxs Año Anterior", key: "lastYearPax" },
      { label: "# Cheques", key: "checksCount" },
      { label: "Paxs / Cheque", key: "paxPerCheck" },
      { label: "Valor Cheque Promedio", key: "averageCheckValue" },
      {
        label: "Valor Cheque Promedio Año Anterior",
        key: "lastYearAverageCheckValue",
      },
      { label: "Costo", key: "cost" },
      { label: "% Costo Vs Ventas", key: "costPercentage" },
      { label: "RPE Real", key: "realRPE" },
      { label: "RPE Presupuesto", key: "budgetRPE" },
      { label: "RPE Diferencia", key: "rpeDifference" },
    ],
  },
  {
    report: REPORT_KEY.REPVOI_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Número de Ticket", key: "ticketNumber" },
      { label: "Producto", key: "product" },
      { label: "Descripción Void", key: "voidDescription" },
      { label: "Importe Voids", key: "voidAmount" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "% Void / Venta Ticket", key: "voidPercentage" },
      { label: "Empleado", key: "employee" },
      { label: "Aprobó", key: "approvedBy" },
      { label: "Hora Abre", key: "openTime" },
      { label: "Hora Cierra", key: "closeTime" },
    ],
  },
  {
    report: REPORT_KEY.REPCUP_01,
    headers: [
      { label: "Cheque", key: "check" },
      { label: "Consumo", key: "consumption" },
      { label: "Precio por consumo", key: "pricePerConsumption" },
      { label: "Diferencia", key: "difference" },
      { label: "Tipoo de cambio cliente", key: "exchangeRateClient" },
      { label: "Clientes", key: "clients" },
      { label: "PAX", key: "pax" },
      { label: "Folio cupones MXN", key: "folioCouponsMXN" },
      { label: "Folio cupones USD", key: "folioCouponsUSD" },
      { label: "Valor MXN", key: "valueMXN" },
      { label: "Valor USD", key: "valueUSD" },
      { label: "Vuelo", key: "flight" },
      { label: "Nombre del pasajero", key: "passengerName" },
    ],
  },
  {
    report: REPORT_KEY.REPBAN_01,
    headers:[
      { label: "Centro de consumo", key: "cdc" },
      { label: "CDC Num", key: "cdcId" },
      { label: "Monto Recibido en Dolares", key: "usdAmount" },
      { label: "Cambio en Dolares", key: "exchangeRate" },
      { label: "Monto Real", key: "realAmount" },
      { label: "Monto Corte de Caja", key: "meraAmount" },
      { label: "Diferencia", key: "difference" },
    ]
  },
  {
    report: REPORT_KEY.REPBAN_02,
    headers:[
      { label: "Tipo de operación", key: "operationType" },
      { label: "Fecha y hora", key: "dateTime" },
      { label: "Codigo de comercio", key: "commerceCode" },
      { label: "Cajero", key: "cashier" },
      { label: "Id", key: "id" }, //! revisar
      { label: "Tipo de moneda recibida", key: "currencyReceivedType" },
      { label: "Cantidad recibida", key: "amountReceived" },
      { label: "Importe de compra", key: "purchaseAmount" },
      { label: "Tipo cambio", key: "exchangeRate" },
      { label: "Moneda del importe", key: "currencyAmount" },
      { label: "idTransaccion", key: "transactionId" },//! revisar
      { label: "Cambio MXN", key: "exchangeRateMXN" },
      { label: "Cambio USD", key: "exchangeRateUSD" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Operador", key: "operator" },
      { label: "Número de cheque", key: "chequeNumber" },
    ]
  }
];