export const DescountDummyData = {
  report: 1,
  discounts: [
    {
      venta: "2025-06-15 03:58:22.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Gerentes",
      s: "960.35",
      ventaTotal: "1114.00",
      ticket: "86.2",
      empleado: "ALEXA MARIA",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 08:16:06.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Incentivos",
      s: "452.59",
      ventaTotal: "525.00",
      ticket: "86.2",
      empleado: "XOCHITL GUADALUPE",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 05:23:24.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Gerentes",
      s: "99.14",
      ventaTotal: "115.00",
      ticket: "86.2",
      empleado: "DENYSE KRYSTAL",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 01:42:29.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento $",
      s: "1768.97",
      ventaTotal: "2052.00",
      ticket: "86.2",
      empleado: "MARGARITA DEL CARMEN",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 07:53:34.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento $",
      s: "884.48",
      ventaTotal: "1025.99",
      ticket: "86.2",
      empleado: "ZAIDA DAMARIS",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 09:04:29.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Incentivos",
      s: "1162.93",
      ventaTotal: "1349.01",
      ticket: "86.2",
      empleado: "ALEXA MARIA",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 10:47:25.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Incentivos",
      s: "288.79",
      ventaTotal: "335.00",
      ticket: "86.2",
      empleado: "MARITZA MARICELA",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 11:29:48.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "762.91",
      ventaTotal: "884.96",
      ticket: "86.2",
      empleado: "ANTONIO",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 04:44:23.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento % ",
      s: "221.12",
      ventaTotal: "256.50",
      ticket: "86.2",
      empleado: "JORGE ALEXANDER PUON AVALOS",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 05:39:22.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Empleado Aeroportuario",
      s: "118.32",
      ventaTotal: "137.25",
      ticket: "86.2",
      empleado: "ERICK EMMANUEL",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 06:34:26.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento $",
      s: "442.24",
      ventaTotal: "513.00",
      ticket: "86.2",
      empleado: "JORGE ALEXANDER PUON AVALOS",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 05:31:50.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "366.38",
      ventaTotal: "425.00",
      ticket: "86.2",
      empleado: "ABRAHAM",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 02:17:26.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Empleado Aeroportuario",
      s: "113.02",
      ventaTotal: "131.10",
      ticket: "86.2",
      empleado: "JARED ABRAHAM",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 09:21:04.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Empleado Mera",
      s: "1115.93",
      ventaTotal: "1294.47",
      ticket: "86.2",
      empleado: "ALEXA MARIA",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 04:17:18.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "378.44",
      ventaTotal: "439.00",
      ticket: "86.2",
      empleado: "JARED ABRAHAM",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 07:30:02.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "1408.60",
      ventaTotal: "1634.00",
      ticket: "86.2",
      empleado: "CARLOS MIGUEL",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 08:42:01.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "331.05",
      ventaTotal: "384.00",
      ticket: "86.2",
      empleado: "ERICK EMMANUEL",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 09:50:06.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Empleado Mera",
      s: "191.81",
      ventaTotal: "222.50",
      ticket: "86.2",
      empleado: "MARITZA MARICELA",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 02:13:12.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "387.08",
      ventaTotal: "449.02",
      ticket: "86.2",
      empleado: "JESUS ANTONIO",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 01:14:14.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento Spills",
      s: "344.83",
      ventaTotal: "400.00",
      ticket: "86.2",
      empleado: "GUADLUPE DE JESUS",
      aprobo: "Sin empleado",
    },
    {
      venta: "2025-06-15 04:40:01.0",
      centroDeConsumo: "MARGARITAVILLE FC CUN T3",
      descuento: "Descuento % ",
      s: "270.26",
      ventaTotal: "313.50",
      ticket: "86.2",
      empleado: "VICTOR MANUEL",
      aprobo: "Sin empleado",
    },
  ],
};

export const PMIXGeneralDummyData = {
  report: 2,
  pmixGeneral: [
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas No Alcoholicas",
      family: "Aguas y Refrescos",
      key: "200100080",
      item: "BT EVIAN 500",
      totalSale: 348873.91,
      voids: 4931.08,
      discounts: 1119.47,
      netSales: 342823.36,
      quantity: 3069,
      categoryPercentage: "15,6%",
      familyPercentage: "61,5%",
      cost: 67134.98,
      costPercentage: "19,6%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      key: "100400007",
      item: "CHICKEN STRIPS",
      totalSale: 345928.0,
      voids: 1965.5,
      discounts: 1659.59,
      netSales: 342302.91,
      quantity: 875,
      categoryPercentage: "12,3%",
      familyPercentage: "33,5%",
      cost: 45495.45,
      costPercentage: "13,3%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Hamburguesas",
      key: "101700006",
      item: "HAMB QUESO",
      totalSale: 248553.6,
      voids: 365.52,
      discounts: 1463.67,
      netSales: 246724.41,
      quantity: 679,
      categoryPercentage: "8,9%",
      familyPercentage: "71,1%",
      cost: 55603.85,
      costPercentage: "22,5%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Sandwich Caliente",
      key: "100600002",
      item: "BEACH CLUB",
      totalSale: 214224.66,
      voids: 860.34,
      discounts: 2137.4,
      netSales: 211226.92,
      quantity: 496,
      categoryPercentage: "7,6%",
      familyPercentage: "55,8%",
      cost: 61244.59,
      costPercentage: "29,0%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Platos Fuertes",
      key: "100500017",
      item: "CANTIN P. ENEG",
      totalSale: 183508.86,
      voids: 1256.91,
      discounts: 1611.49,
      netSales: 180640.46,
      quantity: 435,
      categoryPercentage: "6,5%",
      familyPercentage: "29,0%",
      cost: 47602.88,
      costPercentage: "26,4%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Platos Fuertes",
      key: "100500005",
      item: "QUESA CHICKEN",
      totalSale: 152981.28,
      voids: 342.24,
      discounts: 1144.08,
      netSales: 151494.96,
      quantity: 446,
      categoryPercentage: "5,5%",
      familyPercentage: "24,3%",
      cost: 21666.41,
      costPercentage: "14,3%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      key: "100400013",
      item: "NACHOS POLLO",
      totalSale: 148194.52,
      voids: 0.0,
      discounts: 346.72,
      netSales: 147847.8,
      quantity: 316,
      categoryPercentage: "5,3%",
      familyPercentage: "14,5%",
      cost: 32646.75,
      costPercentage: "22,1%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      key: "100400020",
      item: "GUACAMOLIER",
      totalSale: 138671.4,
      voids: 1981.02,
      discounts: 1751.75,
      netSales: 134938.63,
      quantity: 414,
      categoryPercentage: "4,9%",
      familyPercentage: "13,2%",
      cost: 18450.24,
      costPercentage: "13,7%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Licores Directos",
      key: "201100856",
      item: "CAZADOR REPO D",
      totalSale: 106017.34,
      voids: 0.0,
      discounts: 437.77,
      netSales: 105579.57,
      quantity: 286,
      categoryPercentage: "4,8%",
      familyPercentage: "16,5%",
      cost: 9679.9,
      costPercentage: "9,2%",
    },
    {
      date: "2024-may.",
      subsidiary: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Cervezas",
      key: "200600045",
      item: "DRAFT LGR 20",
      totalSale: 96604.34,
      voids: 672.42,
      discounts: 209.95,
      netSales: 95721.97,
      quantity: 428,
      categoryPercentage: "4,4%",
      familyPercentage: "24,1%",
      cost: 5131.72,
      costPercentage: "5,4%",
    },
  ],
};

export const PMIXEmployeeDummyData = {
  report: 3,
  pmixEmployee: [
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas No Alcoholicas",
      family: "Aguas y Refrescos",
      key: "200100080",
      product: "BT EVIAN 500",
      netSales: 12654.3,
      quantity: 113,
      cost: 2471.9,
      costPercentage: "19,5%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      key: "100400007",
      product: "CHICKEN STRIPS",
      netSales: 10119.47,
      quantity: 26,
      cost: 1351.86,
      costPercentage: "13,4%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Licores Directos",
      key: "201100873",
      product: "HERRADU REP D",
      netSales: 6671.13,
      quantity: 19,
      cost: 1161.68,
      costPercentage: "17,4%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Platos Fuertes",
      key: "100500005",
      product: "QUESA CHICKEN",
      netSales: 5133.6,
      quantity: 15,
      cost: 728.69,
      costPercentage: "14,2%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Licores Directos",
      key: "201100954",
      product: "PATRON REP T",
      netSales: 8551.68,
      quantity: 16,
      cost: 1344.82,
      costPercentage: "15,7%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Ensaladas y Sopas",
      key: "100300005",
      product: "ENS CARIBEÑA",
      netSales: 2517.52,
      quantity: 8,
      cost: 404.92,
      costPercentage: "16,1%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Licores Directos",
      key: "201100856",
      product: "CAZADOR REPO D",
      netSales: 3336.21,
      quantity: 9,
      cost: 304.61,
      costPercentage: "9,1%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      key: "100400013",
      product: "NACHOS POLLO",
      netSales: 5158.67,
      quantity: 11,
      cost: 1136.44,
      costPercentage: "22,0%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Sandwich Caliente",
      key: "100600002",
      product: "BEACH CLUB",
      netSales: 6694.59,
      quantity: 16,
      cost: 1975.63,
      costPercentage: "29,5%",
    },
    {
      date: "01/05/2024",
      location: "ABT3",
      employee: "ABRAHAM SALAS ESQUIVEL",
      cdc: "T3 AIR MARGARITAVILLE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Hamburguesas",
      key: "101700006",
      product: "HAMB QUESO",
      netSales: 7850.24,
      quantity: 22,
      cost: 1801.6,
      costPercentage: "22,9%",
    },
  ],
};

export const VENEmployeeDummyData = {
  report: 4,
  venEmployee: [
   {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "DIANA LAURA",
        "ventaTotal": 83149.40,
        "voids": 0,
        "descuentos": 234.14,
        "ventasNetas": 83149.40,
        "pax": null,
        "venta": null,
        "numeroCheques": 166,
        "chequePromedio": 500.9000,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "DAVID",
        "ventaTotal": 5803.50,
        "voids": 0,
        "descuentos": 32.33,
        "ventasNetas": 5803.50,
        "pax": null,
        "venta": null,
        "numeroCheques": 9,
        "chequePromedio": 644.8333,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "SANTIAGO",
        "ventaTotal": 11410.00,
        "voids": 0,
        "descuentos": 0,
        "ventasNetas": 11410.00,
        "pax": null,
        "venta": null,
        "numeroCheques": 16,
        "chequePromedio": 713.1250,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "ANA ABIGAIL",
        "ventaTotal": 47923.50,
        "voids": 0,
        "descuentos": 32.33,
        "ventasNetas": 47923.50,
        "pax": null,
        "venta": null,
        "numeroCheques": 102,
        "chequePromedio": 469.8382,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "BRYANN GIOVANNY",
        "ventaTotal": 48557.20,
        "voids": 0,
        "descuentos": 208.44,
        "ventasNetas": 48557.20,
        "pax": null,
        "venta": null,
        "numeroCheques": 91,
        "chequePromedio": 533.5956,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-06-30",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "BIANCA JUDITH",
        "ventaTotal": 38594.00,
        "voids": 0,
        "descuentos": 240.52,
        "ventasNetas": 38594.00,
        "pax": null,
        "venta": null,
        "numeroCheques": 80,
        "chequePromedio": 482.4250,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    },
    {
        "fechaDeVenta": "2025-07-01",
        "ubicacion": null,
        "centroDeConsumo": "JOHNNY ROCKETS FC CUN T2",
        "empleado": "BIANCA JUDITH",
        "ventaTotal": 38594.00,
        "voids": 0,
        "descuentos": 240.52,
        "ventasNetas": 38594.00,
        "pax": null,
        "venta": null,
        "numeroCheques": 80,
        "chequePromedio": 482.4250,
        "alimentos": null,
        "bebidas": null,
        "boutique": null,
        "fotos": null,
        "noClasificada": null
    }
  ],
};

export const VENCatFamDummyData = {
  report: 5,
  venCatFam: [
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas No Alcoholicas",
      family: "Café/Té",
      totalSale: "978.48",
      voids: "0.00",
      discounts: "0.00",
      netSales: "978.48",
      netSalesCategoryPercentage: "28,9%",
      totalPercentage: "0,6%",
      quantity: "13.00",
      cost: "80.53",
      costPercentage: "8,2%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Cervezas",
      totalSale: "910.34",
      voids: "0.00",
      discounts: "0.00",
      netSales: "910.34",
      netSalesCategoryPercentage: "26,9%",
      totalPercentage: "0,6%",
      quantity: "6.00",
      cost: "77.17",
      costPercentage: "8,5%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Condim. Alimentos",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "286.00",
      cost: "0.00",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Desayunos",
      totalSale: "18426.75",
      voids: "245.69",
      discounts: "319.39",
      netSales: "17861.67",
      netSalesCategoryPercentage: "11,7%",
      totalPercentage: "11,4%",
      quantity: "74.00",
      cost: "2270.82",
      costPercentage: "12,7%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas No Alcoholicas",
      family: "Jugos",
      totalSale: "1365.50",
      voids: "0.00",
      discounts: "85.34",
      netSales: "1280.16",
      netSalesCategoryPercentage: "37,8%",
      totalPercentage: "0,8%",
      quantity: "10.00",
      cost: "575.70",
      costPercentage: "45,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Platos Fuertes",
      totalSale: "83595.39",
      voids: "0.00",
      discounts: "400.09",
      netSales: "83195.30",
      netSalesCategoryPercentage: "54,4%",
      totalPercentage: "53,2%",
      quantity: "298.00",
      cost: "12678.77",
      costPercentage: "15,2%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Otros",
      subcategory: "Otros",
      family: "Visitantes",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "416.00",
      cost: "0.00",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Combo",
      totalSale: "2730.88",
      voids: "0.00",
      discounts: "0.00",
      netSales: "2730.88",
      netSalesCategoryPercentage: "1,8%",
      totalPercentage: "1,7%",
      quantity: "32.00",
      cost: "1270.42",
      costPercentage: "46,5%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      totalSale: "24600.10",
      voids: "0.00",
      discounts: "20.56",
      netSales: "24579.54",
      netSalesCategoryPercentage: "16,1%",
      totalPercentage: "15,7%",
      quantity: "128.00",
      cost: "4508.25",
      costPercentage: "18,3%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Limited Time Offer",
      totalSale: "657.79",
      voids: "0.00",
      discounts: "0.00",
      netSales: "657.79",
      netSalesCategoryPercentage: "0,4%",
      totalPercentage: "0,4%",
      quantity: "7.00",
      cost: "8.71",
      costPercentage: "1,3%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Sides/Extras",
      totalSale: "16592.29",
      voids: "0.00",
      discounts: "166.24",
      netSales: "16426.05",
      netSalesCategoryPercentage: "10,7%",
      totalPercentage: "10,5%",
      quantity: "1342.00",
      cost: "9653.44",
      costPercentage: "58,8%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Modificadores con Costo Alim",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "314.00",
      cost: "1148.55",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Vino Otros",
      totalSale: "219.83",
      voids: "0.00",
      discounts: "0.00",
      netSales: "219.83",
      netSalesCategoryPercentage: "6,5%",
      totalPercentage: "0,1%",
      quantity: "1.00",
      cost: "55.00",
      costPercentage: "25,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas Alcoholicas",
      family: "Modificadores con Costo Bebidas",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "2.00",
      cost: "1.91",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Ensaladas y Sopas",
      totalSale: "7448.32",
      voids: "0.00",
      discounts: "0.00",
      netSales: "7448.32",
      netSalesCategoryPercentage: "4,9%",
      totalPercentage: "4,8%",
      quantity: "27.00",
      cost: "1035.02",
      costPercentage: "13,9%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Aerolíneas",
      subcategory: "Aerolineas",
      family: "Aerolineas",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "415.00",
      cost: "0.00",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 GUACAMOLE ANDELE",
      category: "Bebidas",
      subcategory: "Bebidas No Alcoholicas",
      family: "Combo Bebidas",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "10.00",
      cost: "44.86",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Botanas",
      totalSale: "1137.95",
      voids: "0.00",
      discounts: "0.00",
      netSales: "1137.95",
      netSalesCategoryPercentage: "13,6%",
      totalPercentage: "4,4%",
      quantity: "10.00",
      cost: "351.37",
      costPercentage: "30,9%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Condim. Alimentos",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "5.00",
      cost: "0.00",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Otros",
      subcategory: "Otros",
      family: "Visitantes",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "63.00",
      cost: "0.00",
      costPercentage: "0,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Appetizers y Entradas",
      totalSale: "7670.69",
      voids: "525.86",
      discounts: "0.00",
      netSales: "7144.83",
      netSalesCategoryPercentage: "85,7%",
      totalPercentage: "27,7%",
      quantity: "28.00",
      cost: "945.91",
      costPercentage: "13,2%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Sides/Extras",
      totalSale: "56.03",
      voids: "0.00",
      discounts: "0.00",
      netSales: "56.03",
      netSalesCategoryPercentage: "0,7%",
      totalPercentage: "0,2%",
      quantity: "1.00",
      cost: "10.66",
      costPercentage: "19,0%",
    },
    {
      date: "01/jun./25",
      cdc: "T3 MV WELCOME BAR",
      category: "Alimentos",
      subcategory: "Alimentos",
      family: "Modificadores con Costo Alim",
      totalSale: "0.00",
      voids: "0.00",
      discounts: "0.00",
      netSales: "0.00",
      netSalesCategoryPercentage: "0,0%",
      totalPercentage: "0,0%",
      quantity: "2.00",
      cost: "7.66",
      costPercentage: "0,0%",
    },
  ],
};

export const VENPaymentDummyData = {
  report: 6,
  venPayment: [
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3512,
      amount: "135.00",
      netSales: "116.38",
      netSalesWithVAT: "135.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3511,
      amount: "169.00",
      netSales: "145.69",
      netSalesWithVAT: "169.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3510,
      amount: "475.00",
      netSales: "409.48",
      netSalesWithVAT: "475.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3509,
      amount: "349.00",
      netSales: "300.86",
      netSalesWithVAT: "349.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3508,
      amount: "473.00",
      netSales: "407.76",
      netSalesWithVAT: "473.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV AMEXCO",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3507,
      amount: "1187.95",
      netSales: "890.52",
      netSalesWithVAT: "1033.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3506,
      amount: "1236.00",
      netSales: "1065.52",
      netSalesWithVAT: "1236.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3505,
      amount: "304.00",
      netSales: "262.07",
      netSalesWithVAT: "304.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3504,
      amount: "400.20",
      netSales: "300.00",
      netSalesWithVAT: "348.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3503,
      amount: "1004.00",
      netSales: "865.51",
      netSalesWithVAT: "1003.99",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3502,
      amount: "1784.20",
      netSales: "1398.28",
      netSalesWithVAT: "1622.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO USD",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3501,
      amount: "64.00",
      netSales: "917.24",
      netSalesWithVAT: "1064.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO EUROS",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3501,
      amount: "1000.00",
      netSales: "917.24",
      netSalesWithVAT: "1064.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANAMEX",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3500,
      amount: "135.00",
      netSales: "116.38",
      netSalesWithVAT: "135.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3499,
      amount: "11.00",
      netSales: "107.76",
      netSalesWithVAT: "125.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO USD",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3499,
      amount: "114.00",
      netSales: "107.76",
      netSalesWithVAT: "125.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3498,
      amount: "8.50",
      netSales: "154.74",
      netSalesWithVAT: "179.50",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO USD",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3498,
      amount: "171.00",
      netSales: "154.74",
      netSalesWithVAT: "179.50",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3497,
      amount: "479.00",
      netSales: "412.93",
      netSalesWithVAT: "479.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3496,
      amount: "135.00",
      netSales: "116.38",
      netSalesWithVAT: "135.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3495,
      amount: "349.00",
      netSales: "300.86",
      netSalesWithVAT: "349.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV BANCOMER",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3494,
      amount: "964.00",
      netSales: "831.05",
      netSalesWithVAT: "964.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3493,
      amount: "4.00",
      netSales: "1566.39",
      netSalesWithVAT: "1817.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO USD",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3493,
      amount: "475.00",
      netSales: "1566.39",
      netSalesWithVAT: "1817.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3493,
      amount: "1338.00",
      netSales: "1566.39",
      netSalesWithVAT: "1817.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3492,
      amount: "1273.80",
      netSales: "998.28",
      netSalesWithVAT: "1158.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3491,
      amount: "230.00",
      netSales: "198.28",
      netSalesWithVAT: "230.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "TPV ADYEN",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3490,
      amount: "1202.30",
      netSales: "942.24",
      netSalesWithVAT: "1093.00",
      comments: 0,
    },
    {
      date: "16/06/2025",
      location: "ABT3",
      cdc: "T3 AIR MARGARITAVILLE",
      paymentMethod: "EFECTIVO MXP",
      currency: 0,
      exchangeRate: 0,
      ticketNumber: 3489,
      amount: "12.00",
      netSales: "747.41",
      netSalesWithVAT: "866.99",
      comments: 0,
    },
  ],
};
