export enum REPORT_KEY {
  REPDES_01 = 1,
  REPMIX_01 = 2,
  REPMIX_02 = 3,
  REPVEN_01 = 4,
  REPVEN_02 = 5,
  REPVEN_03 = 6,
  REPVEN_04 = 7,
  REPVOI_01 = 8,
  REPCUP_01 = 9,
  REPBAN_01 = 10,
  REPBAN_02 = 11,
  REPSYNC_ERRORS = 100,
}
export enum REPORT_NAME {
  REPSYNC_ERRORS = "Errores de sincronización ",
  REPDES_01 = "Descuentos",
  REPMIX_00 = "P-MIX",
  REPMIX_01 = "General",
  REPMIX_02 = "Empleados",
  REPVEN_00 = "Ventas",
  REPVEN_01 = "Empleados",
  REPVEN_02 = "Categorias y familias",
  REPVEN_03 = "Formas de pago",
  REPVEN_04 = "Ventas vs Descuentos",
  REPVOI_01 = "Voids",
  REPCUP_01 = "Cupones",
  REPBAN_00 = "Bancos",
  REPBAN_01 = "Banamex",
  //REPBAN_02 = "Detalle",
}
//TODO: Falta agregar los reportes de bancos
export const REPORT_CONFIG = [
  {
    report: REPORT_KEY.REPSYNC_ERRORS,
    name: REPORT_NAME.REPSYNC_ERRORS,
    date: false,
    dateRange: false,
    subsidiary: false,
    cdc: false,
    multicdc: false,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPDES_01,
    name: REPORT_NAME.REPDES_01,
    date: false,
    dateRange: true,
    subsidiary: true,
    multicdc: true,
    cdc: false,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPMIX_01,
    name: `${REPORT_NAME.REPMIX_00}: ${REPORT_NAME.REPMIX_01}`,
    date: true,
    dateRange: false,
    subsidiary: true,
    multicdc: false,
    cdc: true,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPMIX_02,
    name: `${REPORT_NAME.REPMIX_00}: ${REPORT_NAME.REPMIX_02}`,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    cdc: true,
    employees: true,
    approver: false,
    categories: true,
    subcategories: true,
    family: true,
    items: true,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPVEN_01,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_01}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    multicdc: true,
    cdc: false,
    employees: false, //Verificar si se necesita luego
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPVEN_02,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_02}`,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    cdc: true,
    employees: false,
    approver: false,
    categories: true,
    subcategories: true,
    family: true,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPVEN_03,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_03}`,
    date: false,
    dateRange: true,
    subsidiary: true,
    multicdc: true,
    cdc: false,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPVEN_04,
    name: `${REPORT_NAME.REPVEN_00}: ${REPORT_NAME.REPVEN_04}`,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    cdc: true,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPVOI_01,
    name: REPORT_NAME.REPVOI_01,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    cdc: true,
    employees: true,
    approver: true,
    categories: false,
    subcategories: false,
    family: false,
    items: true,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
  {
    report: REPORT_KEY.REPCUP_01,
    name: REPORT_NAME.REPCUP_01,
    date: true,
    dateRange: false,
    multicdc: false,
    subsidiary: true,
    cdc: true,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
    {
    report: REPORT_KEY.REPBAN_01,
    name: REPORT_NAME.REPBAN_01,
    date: false,
    dateRange: true,
    subsidiary: true,
    cdc: false,
    multicdc: true,
    employees: false,
    approver: false,
    categories: false,
    subcategories: false,
    family: false,
    items: false,
    paymentMethod: false,
    currency: false,
    exchangeRate: false,
  },
];
//TODO: Falta agregar los reportes de bancos
export const TABLE_CONFIG = [
  {
    report: REPORT_KEY.REPSYNC_ERRORS,
    headers: [
      { label: "ID", key: "id" },
      { label: "ID Transacción", key: "transactionID" },
      { label: "Estado", key: "especialStatus" },
      { label: "Intentos", key: "attempts" },
      { label: "Tipo", key: "type" },
      { label: "Mensaje de error", key: "errorMsg" },
      { label: "Centro de Consumo", key: "onCDC" },
      { label: "Proceso de Error", key: "processOfError" },
      { label: "Atendido", key: "attended" },
      { label: "Fecha/Hora Transacción", key: "creationDate" },
      { label: "Fecha/Hora de ultimo intento", key: "lastAttemptDate" },
    ],
  },
  {
    report: REPORT_KEY.REPDES_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Venta Ticket", key: "discountType" },
      { label: "Importe Descuentos", key: "discountAmount" },
      { label: "Venta Total", key: "totalSale" },
      { label: "% Descuentos / Venta Ticket", key: "discountPercentage" },
      { label: "Empleado", key: "employee" },
      { label: "Aprobador", key: "approver" },
    ],
  },
  {
    report: REPORT_KEY.REPMIX_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "subsidiary" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoria", key: "category" },
      //{ label: "Subcategoria", key: "subcategory" },
      { label: "Familia", key: "family" },
      { label: "Clave", key: "key" },
      { label: "Producto", key: "item" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "# items", key: "quantity" },
      { label: "% Ventas / Categoría", key: "categoryPercentage" },
      { label: "% Ventas / Familia", key: "familyPercentage" },
      { label: "Costo", key: "cost" },
      { label: "%Costo / Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPMIX_02,
    headers: [
      { label: "Fecha Ventas", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Empleado", key: "employee" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoría", key: "category" },
      { label: "Subcategoría", key: "subcategory" },
      { label: "Familia", key: "family" },
      { label: "Clave", key: "key" },
      { label: "Producto", key: "product" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "# items", key: "quantity" },
      { label: "Costo", key: "cost" },
      { label: "% Costo / Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Empleado", key: "employee" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Pax", key: "pax" },
      { label: "Venta/", key: "salePer" },
      { label: "# Cheques", key: "checksCount" },
      { label: "Cheque Promedio", key: "averageCheck" },
      { label: "Alimentos", key: "food" },
      { label: "Bebidas", key: "drinks" },
      { label: "Boutique", key: "boutique" },
      { label: "Fotos", key: "photos" },
      { label: "No clasificada", key: "unclassified" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_02,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Categoría", key: "category" },
      { label: "Subcategoría", key: "subcategory" },
      { label: "Familia", key: "family" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "% Venta Neta / Categoría", key: "netSalesCategoryPercentage" },
      { label: "% Venta / Total", key: "totalPercentage" },
      { label: "# items", key: "quantity" },
      { label: "Costo", key: "cost" },
      { label: "% Costo Vs Ventas", key: "costPercentage" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_03,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Ubicación", key: "location" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Forma de Pago", key: "paymentMethod" },
      { label: "Moneda", key: "currency" },
      { label: "Tipo de cambio", key: "exchangeRate" },
      { label: "# Ticket", key: "ticketNumber" },
      { label: "Importe ($)", key: "amount" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Ventas Netas + IVA", key: "netSalesWithVAT" },
      { label: "Comentarios", key: "comments" },
    ],
  },
  {
    report: REPORT_KEY.REPVEN_04,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Voids", key: "voids" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "Presupuesto", key: "budget" },
      {
        label: "% Diferencia Vs Presupuesto",
        key: "budgetDifferencePercentage",
      },
      { label: "$ Diferencia Vs Presupuesto", key: "budgetDifferenceAmount" },
      { label: "Venta Año Anterior", key: "lastYearSale" },
      {
        label: "% Diferencia Vs Año Anterior",
        key: "lastYearDifferencePercentage",
      },
      { label: "Pax", key: "pax" },
      { label: "Venta / Paxs", key: "salePerPax" },
      { label: "Paxs Año Anterior", key: "lastYearPax" },
      { label: "# Cheques", key: "checksCount" },
      { label: "Paxs / Cheque", key: "paxPerCheck" },
      { label: "Valor Cheque Promedio", key: "averageCheckValue" },
      {
        label: "Valor Cheque Promedio Año Anterior",
        key: "lastYearAverageCheckValue",
      },
      { label: "Costo", key: "cost" },
      { label: "% Costo Vs Ventas", key: "costPercentage" },
      { label: "RPE Real", key: "realRPE" },
      { label: "RPE Presupuesto", key: "budgetRPE" },
      { label: "RPE Diferencia", key: "rpeDifference" },
    ],
  },
  {
    report: REPORT_KEY.REPVOI_01,
    headers: [
      { label: "Fecha de Venta", key: "date" },
      { label: "Centro de consumo", key: "cdc" },
      { label: "Número de Ticket", key: "ticketNumber" },
      { label: "Producto", key: "product" },
      { label: "Descripción Void", key: "voidDescription" },
      { label: "Importe Voids", key: "voidAmount" },
      { label: "Venta Total", key: "totalSale" },
      { label: "Descuentos", key: "discounts" },
      { label: "Ventas Netas", key: "netSales" },
      { label: "% Void / Venta Ticket", key: "voidPercentage" },
      { label: "Empleado", key: "employee" },
      { label: "Aprobó", key: "approvedBy" },
      { label: "Hora Abre", key: "openTime" },
      { label: "Hora Cierra", key: "closeTime" },
    ],
  },
  {
    report: REPORT_KEY.REPCUP_01,
    headers: [
      { label: "Cheque", key: "check" },
      { label: "Consumo", key: "consumption" },
      { label: "Precio por consumo", key: "pricePerConsumption" },
      { label: "Diferencia", key: "difference" },
      { label: "Tipoo de cambio cliente", key: "exchangeRateClient" },
      { label: "Clientes", key: "clients" },
      { label: "PAX", key: "pax" },
      { label: "Folio cupones MXN", key: "folioCouponsMXN" },
      { label: "Folio cupones USD", key: "folioCouponsUSD" },
      { label: "Valor MXN", key: "valueMXN" },
      { label: "Valor USD", key: "valueUSD" },
      { label: "Vuelo", key: "flight" },
      { label: "Nombre del pasajero", key: "passengerName" },
    ],
  },
  {
    report: REPORT_KEY.REPBAN_01,
    headers:[
      { label: "Centro de consumo", key: "cdc" },
      { label: "CDC Num", key: "cdcId" },
      { label: "Monto Recibido en Dolares", key: "usdAmount" },
      { label: "Cambio en Dolares", key: "exchangeRate" },
      { label: "Monto Real", key: "realAmount" },
      { label: "Monto Corte de Caja", key: "meraAmount" },
      { label: "Diferencia", key: "difference" },
    ]
  }
];

//TODO: Falta agregar los reportes de bancos
export const MENU_CONFIG = [
  {
    id: 1,
    categoryName: REPORT_NAME.REPMIX_00,
    subCategories: [
      { id: 1, name: REPORT_NAME.REPMIX_01, reportCode: REPORT_KEY.REPMIX_01 },
      //{ id: 2, name: REPORT_NAME.REPMIX_02, reportCode: REPORT_KEY.REPMIX_02 },
    ],
    reportCode: null,
  },
  {
    id: 2,
    categoryName: REPORT_NAME.REPDES_01,
    subCategories: null,
    reportCode: REPORT_KEY.REPDES_01,
  },
  {
    id: 3,
    categoryName: REPORT_NAME.REPVEN_00,
    subCategories: [
      { id: 1, name: REPORT_NAME.REPVEN_01, reportCode: REPORT_KEY.REPVEN_01 },
      //{ id: 2, name: REPORT_NAME.REPVEN_02, reportCode: REPORT_KEY.REPVEN_02 },
      { id: 3, name: REPORT_NAME.REPVEN_03, reportCode: REPORT_KEY.REPVEN_03 },
      //{ id: 4, name: REPORT_NAME.REPVEN_04, reportCode: REPORT_KEY.REPVEN_04 },
    ],
    reportCode: null,
  },
  /* {
    id: 4,
    categoryName: REPORT_NAME.REPVOI_01,
    subCategories: null,
    reportCode: REPORT_KEY.REPVOI_01,
  },
  {
    id: 5,
    categoryName: REPORT_NAME.REPCUP_01,
    subCategories: null,
    reportCode: REPORT_KEY.REPCUP_01,
  }, */
  // {
  //   id: 6,
  //   categoryName: REPORT_NAME.REPBAN_00,
  //   subCategories:[
  //     { id: 1, name: REPORT_NAME.REPBAN_01, reportCode: REPORT_KEY.REPBAN_01 },
  //   ],
  //   reportCode: null
  // },
  {
    id: 100,
    categoryName: REPORT_NAME.REPSYNC_ERRORS,
    subCategories: null,
    reportCode: REPORT_KEY.REPSYNC_ERRORS,
  },

];

export const FILTER_LABELS = {
  date: 'Fecha',
  dateRange: 'Rango de fechas',
  subsidiary: 'Sucursal',
  cdc: 'Centro de consumo',
  multicdc: 'Centros de consumo',
  employees: 'Empleados',
  approver: 'Aprobador',
  categories: 'Categorías',
  subcategories: 'Subcategorías',
  family: 'Familia',
  items: 'Artículos',
  paymentMethod: 'Método de pago',
  currency: 'Moneda',
  exchangeRate: 'Tipo de cambio'
};
export type FilterKey = keyof Omit<typeof REPORT_CONFIG[0], 'report' | 'name'>;

//TODO Banking constant for report CSV

export const BANKING_TITLEHEADERS = [
  {
    report: REPORT_KEY.REPBAN_01,
    summary: [],
    employee: [],
    commerce: [],
    guide:[]
  }
]