const DescountDummyData = {
      "discounts": [
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open %",
        "discountAmount": 543.09,
        "totalSale": 27817.33,
        "discountPercentage": "2,0%",
        "employee": "DIANA PACHECO VAZQUEZ",
        "approver": "ALDO R. LOBATO SANCHEZ"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open %",
        "discountAmount": 211.64,
        "totalSale": 10856.89,
        "discountPercentage": "1,9%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "AMEYALI RAMOS ICAZA"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 461.21,
        "totalSale": 10856.89,
        "discountPercentage": "4,2%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "AMEYALI RAMOS ICAZA"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 460.34,
        "totalSale": 10856.89,
        "discountPercentage": "4,2%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "OSWALDO CHE POOT"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descuento 50%",
        "discountAmount": 287.07,
        "totalSale": 22338.78,
        "discountPercentage": "1,3%",
        "employee": "NAARAI E MENCIA SALAZAR",
        "approver": "ALDO R. LOBATO SANCHEZ"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descuento 50%",
        "discountAmount": 748.28,
        "totalSale": 4212.06,
        "discountPercentage": "17,8%",
        "employee": "LOURDES NOH ARZAPALO",
        "approver": "JOVANNA ALTAMIRANO MARIN"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descuento 50%",
        "discountAmount": 266.38,
        "totalSale": 10856.89,
        "discountPercentage": "2,5%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "AMEYALI RAMOS ICAZA"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc Meal Gte MA",
        "discountAmount": 1004.30,
        "totalSale": 27817.33,
        "discountPercentage": "3,6%",
        "employee": "DIANA PACHECO VAZQUEZ",
        "approver": "ALDO R. LOBATO SANCHEZ"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc Rel Pub Ali",
        "discountAmount": 253.45,
        "totalSale": 20638.85,
        "discountPercentage": "1,2%",
        "employee": "CECILIA MARTINEZ FRANCO",
        "approver": "OSWALDO CHE POOT"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc Rel Pub Ali",
        "discountAmount": 589.66,
        "totalSale": 589.66,
        "discountPercentage": "100,0%",
        "employee": "DENYSE K SANTOS DOMINGUEZ",
        "approver": "OSWALDO CHE POOT"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 94.83,
        "totalSale": 32935.43,
        "discountPercentage": "0,3%",
        "employee": "LINMER TAH MEDINA",
        "approver": "OSWALDO CHE POOT"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 180.18,
        "totalSale": 27817.33,
        "discountPercentage": "0,6%",
        "employee": "DIANA PACHECO VAZQUEZ",
        "approver": "JOVANNA ALTAMIRANO MARIN"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 524.14,
        "totalSale": 25337.99,
        "discountPercentage": "2,1%",
        "employee": "SULY SAR MTZ SANCHEZ",
        "approver": "OSWALDO CHE POOT"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 85.34,
        "totalSale": 12518.12,
        "discountPercentage": "0,7%",
        "employee": "EVA MA. EVA OCHOA L.",
        "approver": "AMEYALI RAMOS ICAZA"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 436.21,
        "totalSale": 23690.57,
        "discountPercentage": "1,8%",
        "employee": "XOCHITL MORALES MORENO",
        "approver": "JOVANNA ALTAMIRANO MARIN"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 93.96,
        "totalSale": 19248.35,
        "discountPercentage": "0,5%",
        "employee": "SANDRA Y HERNANDEZ BARRER",
        "approver": "Sin Empleado"
        },
        {
        "date": "01/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Desc X Spills",
        "discountAmount": 393.10,
        "totalSale": 19248.35,
        "discountPercentage": "2,0%",
        "employee": "SANDRA Y HERNANDEZ BARRER",
        "approver": "ALDO R. LOBATO SANCHEZ"
        },
        {
        "date": "02/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 209.48,
        "totalSale": 22912.91,
        "discountPercentage": "0,9%",
        "employee": "CARLOS M RAMIREZ PINO",
        "approver": "ALDO R. LOBATO SANCHEZ"
        },
        {
        "date": "02/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 461.21,
        "totalSale": 6237.08,
        "discountPercentage": "7,4%",
        "employee": "LOURDES NOH ARZAPALO",
        "approver": "JOVANNA ALTAMIRANO MARIN"
        },
        {
        "date": "02/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 350.00,
        "totalSale": 15167.22,
        "discountPercentage": "2,3%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "AMEYALI RAMOS ICAZA"
        },
        {
        "date": "02/jun./24",
        "cdc": "T3 AIR MARGARITAVILLE",
        "discountType": "Descto.Open $",
        "discountAmount": 350.00,
        "totalSale": 15167.22,
        "discountPercentage": "2,3%",
        "employee": "CATY J. PACHECO HERNADEZ",
        "approver": "JOVANNA ALTAMIRANO MARIN"
        }
  ]
}

const PMIXGeneralDummyData = {
    "pmixGeneral": [
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas No Alcoholicas",
      "family": "Aguas y Refrescos",
      "key": "200100080",
      "item": "BT EVIAN 500",
      "totalSale": 348873.91,
      "voids": 4931.08,
      "discounts": 1119.47,
      "netSales": 342823.36,
      "quantity": 3069,
      "categoryPercentage": "15,6%",
      "familyPercentage": "61,5%",
      "cost": 67134.98,
      "costPercentage": "19,6%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Appetizers y Entradas",
      "key": "100400007",
      "item": "CHICKEN STRIPS",
      "totalSale": 345928.00,
      "voids": 1965.50,
      "discounts": 1659.59,
      "netSales": 342302.91,
      "quantity": 875,
      "categoryPercentage": "12,3%",
      "familyPercentage": "33,5%",
      "cost": 45495.45,
      "costPercentage": "13,3%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Hamburguesas",
      "key": "101700006",
      "item": "HAMB QUESO",
      "totalSale": 248553.60,
      "voids": 365.52,
      "discounts": 1463.67,
      "netSales": 246724.41,
      "quantity": 679,
      "categoryPercentage": "8,9%",
      "familyPercentage": "71,1%",
      "cost": 55603.85,
      "costPercentage": "22,5%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Sandwich Caliente",
      "key": "100600002",
      "item": "BEACH CLUB",
      "totalSale": 214224.66,
      "voids": 860.34,
      "discounts": 2137.40,
      "netSales": 211226.92,
      "quantity": 496,
      "categoryPercentage": "7,6%",
      "familyPercentage": "55,8%",
      "cost": 61244.59,
      "costPercentage": "29,0%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Platos Fuertes",
      "key": "100500017",
      "item": "CANTIN P. ENEG",
      "totalSale": 183508.86,
      "voids": 1256.91,
      "discounts": 1611.49,
      "netSales": 180640.46,
      "quantity": 435,
      "categoryPercentage": "6,5%",
      "familyPercentage": "29,0%",
      "cost": 47602.88,
      "costPercentage": "26,4%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Platos Fuertes",
      "key": "100500005",
      "item": "QUESA CHICKEN",
      "totalSale": 152981.28,
      "voids": 342.24,
      "discounts": 1144.08,
      "netSales": 151494.96,
      "quantity": 446,
      "categoryPercentage": "5,5%",
      "familyPercentage": "24,3%",
      "cost": 21666.41,
      "costPercentage": "14,3%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Appetizers y Entradas",
      "key": "100400013",
      "item": "NACHOS POLLO",
      "totalSale": 148194.52,
      "voids": 0.00,
      "discounts": 346.72,
      "netSales": 147847.80,
      "quantity": 316,
      "categoryPercentage": "5,3%",
      "familyPercentage": "14,5%",
      "cost": 32646.75,
      "costPercentage": "22,1%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Appetizers y Entradas",
      "key": "100400020",
      "item": "GUACAMOLIER",
      "totalSale": 138671.40,
      "voids": 1981.02,
      "discounts": 1751.75,
      "netSales": 134938.63,
      "quantity": 414,
      "categoryPercentage": "4,9%",
      "familyPercentage": "13,2%",
      "cost": 18450.24,
      "costPercentage": "13,7%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas Alcoholicas",
      "family": "Licores Directos",
      "key": "201100856",
      "item": "CAZADOR REPO D",
      "totalSale": 106017.34,
      "voids": 0.00,
      "discounts": 437.77,
      "netSales": 105579.57,
      "quantity": 286,
      "categoryPercentage": "4,8%",
      "familyPercentage": "16,5%",
      "cost": 9679.90,
      "costPercentage": "9,2%"
    },
    {
      "date": "2024-may.",
      "subsidiary": "ABT3",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas Alcoholicas",
      "family": "Cervezas",
      "key": "200600045",
      "item": "DRAFT LGR 20",
      "totalSale": 96604.34,
      "voids": 672.42,
      "discounts": 209.95,
      "netSales": 95721.97,
      "quantity": 428,
      "categoryPercentage": "4,4%",
      "familyPercentage": "24,1%",
      "cost": 5131.72,
      "costPercentage": "5,4%"
    }
  ]
}

const PMIXEmployeeDummyData = {
    "pmixEmployee": [
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas No Alcoholicas",
      "family": "Aguas y Refrescos",
      "key": "200100080",
      "product": "BT EVIAN 500",
      "netSales": 12654.30,
      "quantity": 113,
      "cost": 2471.90,
      "costPercentage": "19,5%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Appetizers y Entradas",
      "key": "100400007",
      "product": "CHICKEN STRIPS",
      "netSales": 10119.47,
      "quantity": 26,
      "cost": 1351.86,
      "costPercentage": "13,4%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas Alcoholicas",
      "family": "Licores Directos",
      "key": "201100873",
      "product": "HERRADU REP D",
      "netSales": 6671.13,
      "quantity": 19,
      "cost": 1161.68,
      "costPercentage": "17,4%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Platos Fuertes",
      "key": "100500005",
      "product": "QUESA CHICKEN",
      "netSales": 5133.60,
      "quantity": 15,
      "cost": 728.69,
      "costPercentage": "14,2%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas Alcoholicas",
      "family": "Licores Directos",
      "key": "201100954",
      "product": "PATRON REP T",
      "netSales": 8551.68,
      "quantity": 16,
      "cost": 1344.82,
      "costPercentage": "15,7%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Ensaladas y Sopas",
      "key": "100300005",
      "product": "ENS CARIBEÑA",
      "netSales": 2517.52,
      "quantity": 8,
      "cost": 404.92,
      "costPercentage": "16,1%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Bebidas",
      "subcategory": "Bebidas Alcoholicas",
      "family": "Licores Directos",
      "key": "201100856",
      "product": "CAZADOR REPO D",
      "netSales": 3336.21,
      "quantity": 9,
      "cost": 304.61,
      "costPercentage": "9,1%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Appetizers y Entradas",
      "key": "100400013",
      "product": "NACHOS POLLO",
      "netSales": 5158.67,
      "quantity": 11,
      "cost": 1136.44,
      "costPercentage": "22,0%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Sandwich Caliente",
      "key": "100600002",
      "product": "BEACH CLUB",
      "netSales": 6694.59,
      "quantity": 16,
      "cost": 1975.63,
      "costPercentage": "29,5%"
    },
    {
      "date": "01/05/2024",
      "location": "ABT3",
      "employee": "ABRAHAM SALAS ESQUIVEL",
      "cdc": "T3 AIR MARGARITAVILLE",
      "category": "Alimentos",
      "subcategory": "Alimentos",
      "family": "Hamburguesas",
      "key": "101700006",
      "product": "HAMB QUESO",
      "netSales": 7850.24,
      "quantity": 22,
      "cost": 1801.60,
      "costPercentage": "22,9%"
    }
  ]
}